language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm run build
  - mv .travis-gitignore .gitignore
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master